CC = gcc
CFLAGS = -Wall

all: cp cat readln person

cp:
	$(CC) $(CFLAGS) -o cp mycp.c

cat:
	$(CC) $(CFLAGS) -o cat mycat.c	

readln:
	$(CC) $(CFLAGS) -o readln myreadln.c

person:
	$(CC) $(CFLAGS) -o person person.c

clean:
	-rm -f *.o	cp cat readln person	