CC = gcc
CFLAGS = -Wall

all: ex1 ex2 ex3 ex4
 
ex1:
	$(CC) $(CFLAGS) -o ex1 ex1.c

ex2:
	$(CC) $(CFLAGS) -o ex2 ex2.c

ex3:
	$(CC) $(CFLAGS) -o ex3 ex3.c

ex4:
	$(CC) $(CFLAGS) -o ex4 ex4.c

clean:
	-rm -f *.o ex1 ex2 ex3 ex4